/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness of the API and its database
     * @description Round-trips a query to Postgres, so a green response means the connection is genuinely usable rather than merely configured.
     */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The caller's own account */
    get: operations['UsersController_getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the caller's own account */
    patch: operations['UsersController_updateMe'];
    trace?: never;
  };
  '/users/{username}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Look up a User by Username
     * @description Exact match only — see backend/CONTEXT.md on Username.
     */
    get: operations['UsersController_getByUsername'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account
     * @description Works immediately — there is no verification gate.
     */
    post: operations['AuthController_signUp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a token session */
    post: operations['AuthController_signIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's own Expenses
     * @description Every Visibility, newest logged first. Owner-only for now.
     */
    get: operations['ExpensesController_findAll'];
    put?: never;
    /** Log an Expense */
    post: operations['ExpensesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponseDto: {
      /**
       * @example ok
       * @enum {string}
       */
      status: 'ok';
      /**
       * @example up
       * @enum {string}
       */
      database: 'up';
    };
    HealthUnavailableDto: {
      /**
       * @example error
       * @enum {string}
       */
      status: 'error';
      /**
       * @example down
       * @enum {string}
       */
      database: 'down';
    };
    /** @enum {string} */
    SupportedCurrency:
      | 'VND'
      | 'USD'
      | 'EUR'
      | 'GBP'
      | 'JPY'
      | 'SGD'
      | 'AUD'
      | 'CAD'
      | 'KRW'
      | 'THB';
    /** @enum {string} */
    Locale: 'en' | 'vi';
    PrivateUserDto: {
      id: string;
      /** @description The User's unique public handle. */
      username: string;
      displayName: string;
      email: string;
      preferredCurrency: components['schemas']['SupportedCurrency'];
      locale: components['schemas']['Locale'];
      /** @description ISO 8601 */
      createdAt: string;
    };
    UpdateMeDto: {
      locale: components['schemas']['Locale'];
    };
    PublicUserDto: {
      id: string;
      /** @description The User's unique public handle. */
      username: string;
      displayName: string;
    };
    SignUpDto: {
      /** @example minh@spendx.app */
      email: string;
      password: string;
      /**
       * @description The User's unique public handle: 3-30 characters, lowercase letters, digits, and underscores.
       * @example minhtran
       */
      username: string;
      /** @example Minh Trần */
      displayName: string;
      preferredCurrency: components['schemas']['SupportedCurrency'];
      locale: components['schemas']['Locale'];
    };
    AuthResponseDto: {
      accessToken: string;
      user: components['schemas']['PrivateUserDto'];
    };
    SignInDto: {
      /** @example minh@spendx.app */
      email: string;
      password: string;
    };
    /** @enum {string} */
    Category: 'housing' | 'food' | 'leisure' | 'investment' | 'other';
    /** @enum {string} */
    Visibility: 'private' | 'friend_only' | 'public';
    CreateExpenseDto: {
      /** @example Coffee with a friend */
      description: string;
      /**
       * @description The Original Amount, exactly as entered: a positive decimal string with at most 4 decimal places. Never a JSON number.
       * @example 45000.0000
       */
      originalAmount: string;
      originalCurrency: components['schemas']['SupportedCurrency'];
      category: components['schemas']['Category'];
      visibility: components['schemas']['Visibility'];
      /**
       * @description The Expense Date (YYYY-MM-DD). Defaults to the logging day in the fixed app timezone (Asia/Ho_Chi_Minh) when omitted. Backdating is allowed; this never affects the Converted Amount (ADR-0002).
       * @example 2026-08-01
       */
      expenseDate?: string;
    };
    ExpenseDto: {
      id: string;
      description: string;
      /**
       * @description The Original Amount, exactly as entered, as a fixed-scale decimal string (4 decimal places). Never a JSON number.
       * @example 45000.0000
       */
      originalAmount: string;
      originalCurrency: components['schemas']['SupportedCurrency'];
      /**
       * @description The Converted Amount: the Original Amount converted into the owner's Preferred Currency at the logging date's Daily Rate, and frozen. A fixed-scale decimal string (4 decimal places).
       * @example 1.9565
       */
      convertedAmount: string;
      convertedCurrency: components['schemas']['SupportedCurrency'];
      category: components['schemas']['Category'];
      visibility: components['schemas']['Visibility'];
      /**
       * @description YYYY-MM-DD
       * @example 2026-08-01
       */
      expenseDate: string;
      /** @description ISO 8601 — the immutable Logged At. */
      loggedAt: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthUnavailableDto'];
        };
      };
    };
  };
  UsersController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrivateUserDto'];
        };
      };
    };
  };
  UsersController_updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrivateUserDto'];
        };
      };
    };
  };
  UsersController_getByUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicUserDto'];
        };
      };
    };
  };
  AuthController_signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Email or Username already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Invalid email or password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ExpensesController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'][];
        };
      };
    };
  };
  ExpensesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateExpenseDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'];
        };
      };
    };
  };
}
