/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness of the API and its database
     * @description Round-trips a query to Postgres, so a green response means the connection is genuinely usable rather than merely configured.
     */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** The caller's own account */
    get: operations['UsersController_getMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the caller's own account */
    patch: operations['UsersController_updateMe'];
    trace?: never;
  };
  '/users/{username}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Look up a User by Username
     * @description Exact match only — see backend/CONTEXT.md on Username.
     */
    get: operations['UsersController_getByUsername'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an account
     * @description Works immediately — there is no verification gate.
     */
    post: operations['AuthController_signUp'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/sign-in': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Start a token session */
    post: operations['AuthController_signIn'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's own Expenses
     * @description Every Visibility, newest logged first. Owner-only for now.
     */
    get: operations['ExpensesController_findAll'];
    put?: never;
    /** Log an Expense */
    post: operations['ExpensesController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses/statistics': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's personal statistics
     * @description Current-ISO-week and current-calendar-month totals and Category breakdowns, each against the immediately preceding Period, in the caller's Preferred Currency. Owner-scoped over every Visibility — full spending appears only here (ADR-0003).
     */
    get: operations['ExpensesController_statistics'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete an Expense
     * @description Owner-only. Removes it everywhere, with no residue.
     */
    delete: operations['ExpensesController_remove'];
    options?: never;
    head?: never;
    /**
     * Edit an Expense
     * @description Owner-only. The Converted Amount is re-derived at the original logging date's Daily Rate, never the edit date's (ADR-0002).
     */
    patch: operations['ExpensesController_update'];
    trace?: never;
  };
  '/friend-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's pending Friend Requests
     * @description Both directions, each newest first.
     */
    get: operations['FriendRequestsController_findAll'];
    put?: never;
    /**
     * Send a Friend Request
     * @description See backend/CONTEXT.md — Friend Request.
     */
    post: operations['FriendRequestsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friend-requests/{id}/accept': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Accept a Friend Request
     * @description Recipient only. Creates the Friendship.
     */
    post: operations['FriendRequestsController_accept'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friend-requests/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Decline or cancel a Friend Request
     * @description The recipient declines or the sender cancels — the same endpoint, role checked.
     */
    delete: operations['FriendRequestsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The caller's Friends
     * @description Ordered by Username. See backend/CONTEXT.md — Friendship.
     */
    get: operations['FriendshipsController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/friends/{username}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Unfriend a User */
    delete: operations['FriendshipsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/{username}/expenses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * A Friend's Shareable Expenses
     * @description Friend-only and Public Expenses only, never Private — newest logged first, converted into the caller's own Preferred Currency. Requires an existing Friendship with the owner.
     */
    get: operations['UserExpensesController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthResponseDto: {
      /**
       * @example ok
       * @enum {string}
       */
      status: 'ok';
      /**
       * @example up
       * @enum {string}
       */
      database: 'up';
    };
    HealthUnavailableDto: {
      /**
       * @example error
       * @enum {string}
       */
      status: 'error';
      /**
       * @example down
       * @enum {string}
       */
      database: 'down';
    };
    /** @enum {string} */
    SupportedCurrency:
      | 'VND'
      | 'USD'
      | 'EUR'
      | 'GBP'
      | 'JPY'
      | 'SGD'
      | 'AUD'
      | 'CAD'
      | 'KRW'
      | 'THB';
    /** @enum {string} */
    Locale: 'en' | 'vi';
    PrivateUserDto: {
      id: string;
      /** @description The User's unique public handle. */
      username: string;
      displayName: string;
      email: string;
      preferredCurrency: components['schemas']['SupportedCurrency'];
      locale: components['schemas']['Locale'];
      /** @description ISO 8601 */
      createdAt: string;
    };
    UpdateMeDto: {
      preferredCurrency?: components['schemas']['SupportedCurrency'];
      locale?: components['schemas']['Locale'];
    };
    PublicUserDto: {
      id: string;
      /** @description The User's unique public handle. */
      username: string;
      displayName: string;
    };
    SignUpDto: {
      /** @example minh@spendx.app */
      email: string;
      password: string;
      /**
       * @description The User's unique public handle: 3-30 characters, lowercase letters, digits, and underscores.
       * @example minhtran
       */
      username: string;
      /** @example Minh Trần */
      displayName: string;
      preferredCurrency: components['schemas']['SupportedCurrency'];
      locale: components['schemas']['Locale'];
    };
    AuthResponseDto: {
      accessToken: string;
      user: components['schemas']['PrivateUserDto'];
    };
    SignInDto: {
      /** @example minh@spendx.app */
      email: string;
      password: string;
    };
    /** @enum {string} */
    Category: 'housing' | 'food' | 'leisure' | 'investment' | 'other';
    /** @enum {string} */
    Visibility: 'private' | 'friend_only' | 'public';
    CreateExpenseDto: {
      /** @example Coffee with a friend */
      description: string;
      /**
       * @description The Original Amount, exactly as entered: a positive decimal string with at most 4 decimal places. Never a JSON number.
       * @example 45000.0000
       */
      originalAmount: string;
      originalCurrency: components['schemas']['SupportedCurrency'];
      category: components['schemas']['Category'];
      visibility: components['schemas']['Visibility'];
      /**
       * @description The Expense Date (YYYY-MM-DD). Defaults to the logging day in the fixed app timezone (Asia/Ho_Chi_Minh) when omitted. Backdating is allowed; this never affects the Converted Amount (ADR-0002).
       * @example 2026-08-01
       */
      expenseDate?: string;
    };
    ExpenseDto: {
      id: string;
      description: string;
      /**
       * @description The Original Amount, exactly as entered and immutable after logging (ADR-0008), as a fixed-scale decimal string (4 decimal places). Never a JSON number.
       * @example 45000.0000
       */
      originalAmount: string;
      originalCurrency: components['schemas']['SupportedCurrency'];
      /**
       * @description The Converted Amount: the Conversion Snapshot's entry for the reader's Preferred Currency — derived at the logging date's Daily Rate and frozen (ADR-0008). A fixed-scale decimal string (4 decimal places).
       * @example 1.9565
       */
      convertedAmount: string;
      convertedCurrency: components['schemas']['SupportedCurrency'];
      category: components['schemas']['Category'];
      visibility: components['schemas']['Visibility'];
      /**
       * @description YYYY-MM-DD
       * @example 2026-08-01
       */
      expenseDate: string;
      /** @description ISO 8601 — the immutable Logged At. */
      loggedAt: string;
    };
    CategoryTotalDto: {
      category: components['schemas']['Category'];
      /**
       * @description The summed Converted Amount for this Category within the Period, in the owner's Preferred Currency, as a fixed-scale decimal string (4 decimal places). Never a JSON number.
       * @example 450000.0000
       */
      total: string;
    };
    PeriodStatisticsDto: {
      /**
       * @description YYYY-MM-DD, inclusive.
       * @example 2026-08-03
       */
      start: string;
      /**
       * @description YYYY-MM-DD, inclusive.
       * @example 2026-08-09
       */
      end: string;
      /**
       * @description The summed Converted Amount over the Period, in the owner's Preferred Currency, as a fixed-scale decimal string (4 decimal places). Never a JSON number.
       * @example 4850000.0000
       */
      total: string;
      /**
       * @description The same total for the immediately preceding Period of the same length (previous ISO week or previous calendar month), for comparison.
       * @example 3200000.0000
       */
      previousTotal: string;
      /** @description Every Category (backend/CONTEXT.md), including zero totals, sorted by total descending; ties broken by the canonical Category order. */
      categories: components['schemas']['CategoryTotalDto'][];
    };
    StatisticsDto: {
      /** @description The owner's Preferred Currency — every total below is in it. */
      currency: components['schemas']['SupportedCurrency'];
      /** @description The current ISO week (Monday through Sunday). */
      week: components['schemas']['PeriodStatisticsDto'];
      /** @description The current calendar month. */
      month: components['schemas']['PeriodStatisticsDto'];
    };
    UpdateExpenseDto: {
      /** @example Coffee with a friend */
      description?: string;
      category?: components['schemas']['Category'];
      visibility?: components['schemas']['Visibility'];
      /**
       * @description The Expense Date (YYYY-MM-DD). Defaults to the logging day in the fixed app timezone (Asia/Ho_Chi_Minh) when omitted. Backdating is allowed; this never affects the Converted Amount (ADR-0002).
       * @example 2026-08-01
       */
      expenseDate?: string;
    };
    CreateFriendRequestDto: {
      /**
       * @description The recipient's Username — exact match only, same as GET /users/:username (see backend/CONTEXT.md — Username).
       * @example minhtran
       */
      username: string;
    };
    FriendRequestDto: {
      id: string;
      sender: components['schemas']['PublicUserDto'];
      recipient: components['schemas']['PublicUserDto'];
      /** @description ISO 8601 */
      createdAt: string;
    };
    FriendRequestsDto: {
      /** @description Requests sent to the caller, newest first. */
      incoming: components['schemas']['FriendRequestDto'][];
      /** @description Requests the caller sent, newest first. */
      outgoing: components['schemas']['FriendRequestDto'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponseDto'];
        };
      };
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthUnavailableDto'];
        };
      };
    };
  };
  UsersController_getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrivateUserDto'];
        };
      };
    };
  };
  UsersController_updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PrivateUserDto'];
        };
      };
    };
  };
  UsersController_getByUsername: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicUserDto'];
        };
      };
    };
  };
  AuthController_signUp: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignUpDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Email or Username already taken */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_signIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignInDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Invalid email or password */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ExpensesController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'][];
        };
      };
    };
  };
  ExpensesController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateExpenseDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'];
        };
      };
    };
  };
  ExpensesController_statistics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StatisticsDto'];
        };
      };
    };
  };
  ExpensesController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not the caller's Expense, or no such Expense. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ExpensesController_update: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateExpenseDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'];
        };
      };
      /** @description Not the caller's Expense, or no such Expense. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FriendRequestsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestsDto'];
        };
      };
    };
  };
  FriendRequestsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFriendRequestDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FriendRequestDto'];
        };
      };
      /** @description Sending to yourself. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown Username. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Already Friends, or a Friend Request is already pending between the two, in either direction. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FriendRequestsController_accept: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicUserDto'];
        };
      };
      /** @description No such Friend Request, or the caller is not its recipient. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FriendRequestsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Removed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such Friend Request, or the caller is neither party. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FriendshipsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicUserDto'][];
        };
      };
    };
  };
  FriendshipsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unfriended. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No such Friendship. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UserExpensesController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ExpenseDto'][];
        };
      };
      /** @description Not Friends with this User (including a declined/cancelled Friend Request, an unfriended former Friend, or the caller's own Username). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unknown Username. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
